"""
IntelliCredit CAM Exporter
===========================
Exports Credit Appraisal Memo to PDF and DOCX formats with professional formatting.
"""

import os
import re
import logging
from typing import Dict, Any, Optional
from datetime import datetime

logger = logging.getLogger("intellicredit.cam_exporter")

# Break long tokens (e.g., URLs) for PDF layout safety
def _break_long_words(text: str, max_len: int = 60) -> str:
    if not text:
        return text
    parts = []
    for token in text.split(" "):
        if len(token) <= max_len:
            parts.append(token)
            continue
        # Insert soft breaks every max_len chars
        chunks = [token[i:i+max_len] for i in range(0, len(token), max_len)]
        parts.append(" ".join(chunks))
    return " ".join(parts)

def _pdf_safe(text: str) -> str:
    """
    FPDF core fonts are latin-1; replace unsupported unicode (emoji, etc.)
    to avoid layout exceptions.
    """
    if text is None:
        return ""
    try:
        return text.encode("latin-1", "replace").decode("latin-1")
    except Exception:
        return str(text)

# ─────────────────────────────────────────────────────────────────
# DOCX EXPORT
# ─────────────────────────────────────────────────────────────────
def export_cam_to_docx(
    cam_markdown: str,
    metadata: Dict[str, Any],
    output_path: Optional[str] = None,
) -> str:
    """
    Convert CAM markdown to a professionally formatted DOCX document.
    """
    try:
        from docx import Document
        from docx.shared import Inches, Pt, Cm, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        logger.error("python-docx not installed.")
        raise ImportError("python-docx is required for DOCX export")

    doc = Document()
    
    # Page setup
    section = doc.sections[0]
    section.top_margin = Cm(2)
    section.bottom_margin = Cm(2)
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)

    # Title
    title = doc.add_heading("Credit Appraisal Memo", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle / metadata
    company_name = metadata.get("company_name", "Unknown Company")
    application_id = metadata.get("application_id", "N/A")

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"{company_name}\n")
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(0x0B, 0x1D, 0x51)
    run.bold = True

    run2 = subtitle.add_run(f"Application ID: {application_id}")
    run2.font.size = Pt(10)
    run2.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    doc.add_paragraph()  # Spacer

    # Notice
    conf_para = doc.add_paragraph()
    conf_run = conf_para.add_run(
        "CONFIDENTIAL — For internal use only. This document contains proprietary "
        "credit analysis generated by the IntelliCredit AI Decision Engine."
    )
    conf_run.font.size = Pt(8)
    conf_run.font.italic = True
    conf_run.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)

    doc.add_paragraph()

    # Parse markdown (simplified)
    lines = cam_markdown.split("\n")
    for line in lines:
        line = line.rstrip()
        if line.startswith("### "):
            doc.add_heading(line[4:].strip(), level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:].strip(), level=2)
        elif line.startswith("# "):
            doc.add_heading(line[2:].strip(), level=1)
        elif line.startswith("---"):
            doc.add_paragraph("─" * 60)
        elif line.startswith("- ") or line.startswith("* "):
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(line[2:].strip().replace("**", ""))
        elif line.strip() and not line.startswith("|"):
            p = doc.add_paragraph()
            p.add_run(line.replace("**", ""))

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    f_run = footer.add_run(
        "DISCLAIMER: This CAM is generated by the IntelliCredit AI engine. "
        "All ML risk scores are deterministic and transparent. "
        "Final lending decisions require human review per RBI DL Guidelines 6(a)."
    )
    f_run.font.size = Pt(7)
    f_run.font.italic = True
    f_run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    if output_path is None:
        os.makedirs("./exports", exist_ok=True)
        output_path = f"./exports/CAM_{application_id}.docx"

    doc.save(output_path)
    return output_path

# ─────────────────────────────────────────────────────────────────
# PDF EXPORT
# ─────────────────────────────────────────────────────────────────
def export_cam_to_pdf(
    cam_markdown: str,
    metadata: Dict[str, Any],
    output_path: Optional[str] = None,
) -> str:
    """
    Convert CAM markdown to a formatted PDF.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        logger.error("fpdf2 not installed.")
        raise ImportError("fpdf2 is required for PDF export")

    company_name = metadata.get("company_name", "Unknown Company")
    application_id = metadata.get("application_id", "N/A")

    class CAMReport(FPDF):
        def header(self):
            self.set_font("Helvetica", "B", 8)
            self.set_text_color(150, 150, 150)
            usable_w = self.w - self.l_margin - self.r_margin
            self.cell(usable_w, 5, _pdf_safe(f"CONFIDENTIAL | IntelliCredit CAM | {application_id}"), align="C", ln=1)
            self.ln(3)
            
        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 7)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    pdf = CAMReport()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_left_margin(15)
    pdf.set_right_margin(15)
    pdf.add_page()
    usable_w = pdf.w - pdf.l_margin - pdf.r_margin

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(11, 29, 81)
    pdf.cell(usable_w, 10, "Credit Appraisal Memo", align="C", ln=1)
    
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(usable_w, 8, _pdf_safe(company_name), align="C", ln=1)
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(usable_w, 6, _pdf_safe(f"Application ID: {application_id}"), align="C", ln=1)
    pdf.ln(5)

    # Simplified markdown parsing
    lines = cam_markdown.split("\n")
    for line in lines:
        stripped = line.rstrip()
        clean = re.sub(r"\*\*(.*?)\*\*", r"\1", stripped)
        clean = re.sub(r"\*(.*?)\*", r"\1", clean)
        clean = _break_long_words(clean, max_len=60)
        clean = _pdf_safe(clean)

        if stripped.startswith("### "):
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 60, 120)
            pdf.multi_cell(usable_w, 5, clean[4:].strip())
        elif stripped.startswith("## "):
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(11, 29, 81)
            pdf.multi_cell(usable_w, 6, clean[3:].strip())
        elif stripped.startswith("# "):
            pdf.ln(5)
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(11, 29, 81)
            pdf.multi_cell(usable_w, 7, clean[2:].strip())
        elif stripped.startswith("- ") or stripped.startswith("* "):
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(0, 0, 0)
            pdf.multi_cell(usable_w, 5, f"- {clean[2:].strip()}")
        elif stripped.strip() and not stripped.startswith("|") and not stripped.startswith("---"):
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(0, 0, 0)
            pdf.multi_cell(usable_w, 5, clean)
            
    if output_path is None:
        os.makedirs("./exports", exist_ok=True)
        output_path = f"./exports/CAM_{application_id}.pdf"

    pdf.output(output_path)
    return output_path
