"""
IntelliCredit CAM Exporter
===========================
Exports Credit Appraisal Memo to PDF and DOCX formats with professional formatting.
"""

import os
import re
import logging
from typing import Dict, Any, Optional
from datetime import datetime

logger = logging.getLogger("intellicredit.cam_exporter")

# Break long tokens (e.g., URLs) for PDF layout safety
def _break_long_words(text: str, max_len: int = 60) -> str:
    if not text:
        return text
    parts = []
    for token in text.split(" "):
        if len(token) <= max_len:
            parts.append(token)
            continue
        # Insert soft breaks every max_len chars
        chunks = [token[i:i+max_len] for i in range(0, len(token), max_len)]
        parts.append(" ".join(chunks))
    return " ".join(parts)

def _pdf_safe(text: str) -> str:
    """
    FPDF core fonts are latin-1; replace unsupported unicode (emoji, etc.)
    to avoid layout exceptions.
    """
    if text is None:
        return ""
    try:
        return text.encode("latin-1", "replace").decode("latin-1")
    except Exception:
        return str(text)

# ─────────────────────────────────────────────────────────────────
# DOCX EXPORT
# ─────────────────────────────────────────────────────────────────
def export_cam_to_docx(
    cam_markdown: str,
    metadata: Dict[str, Any],
    output_path: Optional[str] = None,
) -> str:
    """
    Convert CAM markdown to a professionally formatted DOCX document.
    """
    try:
        from docx import Document
        from docx.shared import Inches, Pt, Cm, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        logger.error("python-docx not installed.")
        raise ImportError("python-docx is required for DOCX export")

    doc = Document()
    
    # Page setup
    section = doc.sections[0]
    section.top_margin = Cm(2)
    section.bottom_margin = Cm(2)
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)

    # Title
    title = doc.add_heading("Credit Appraisal Memo", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle / metadata
    company_name = metadata.get("company_name", "Unknown Company")
    application_id = metadata.get("application_id", "N/A")

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"{company_name}\n")
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(0x0B, 0x1D, 0x51)
    run.bold = True

    run2 = subtitle.add_run(f"Application ID: {application_id}")
    run2.font.size = Pt(10)
    run2.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    doc.add_paragraph()  # Spacer

    # Notice
    conf_para = doc.add_paragraph()
    conf_run = conf_para.add_run(
        "CONFIDENTIAL — For internal use only. This document contains proprietary "
        "credit analysis generated by the IntelliCredit AI Decision Engine."
    )
    conf_run.font.size = Pt(8)
    conf_run.font.italic = True
    conf_run.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)

    doc.add_paragraph()

    # Parse markdown (simplified)
    lines = cam_markdown.split("\n")
    for line in lines:
        line = line.rstrip()
        if line.startswith("### "):
            doc.add_heading(line[4:].strip(), level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:].strip(), level=2)
        elif line.startswith("# "):
            doc.add_heading(line[2:].strip(), level=1)
        elif line.startswith("---"):
            doc.add_paragraph("─" * 60)
        elif line.startswith("- ") or line.startswith("* "):
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(line[2:].strip().replace("**", ""))
        elif line.strip() and not line.startswith("|"):
            p = doc.add_paragraph()
            p.add_run(line.replace("**", ""))

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    f_run = footer.add_run(
        "DISCLAIMER: This CAM is generated by the IntelliCredit AI engine. "
        "All ML risk scores are deterministic and transparent. "
        "Final lending decisions require human review per RBI DL Guidelines 6(a)."
    )
    f_run.font.size = Pt(7)
    f_run.font.italic = True
    f_run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    if output_path is None:
        os.makedirs("./exports", exist_ok=True)
        output_path = f"./exports/CAM_{application_id}.docx"

    doc.save(output_path)
    return output_path

# ─────────────────────────────────────────────────────────────────
# PDF EXPORT
# ─────────────────────────────────────────────────────────────────
def export_cam_to_pdf(
    cam_markdown: str,
    metadata: Dict[str, Any],
    output_path: Optional[str] = None,
) -> str:
    """
    Convert CAM markdown to a formatted PDF with full professional layout.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        logger.error("fpdf2 not installed.")
        raise ImportError("fpdf2 is required for PDF export")

    company_name = metadata.get("company_name", "Unknown Company")
    application_id = metadata.get("application_id", "N/A")

    class CAMReport(FPDF):
        def header(self):
            if self.page_no() > 1:
                self.set_font("Helvetica", "B", 8)
                self.set_text_color(150, 150, 150)
                usable_w = self.w - self.l_margin - self.r_margin
                self.cell(usable_w, 10, _pdf_safe(f"CONFIDENTIAL | IntelliCredit CAM | {application_id}"), align="R", ln=1)
                self.ln(5)
            
        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    pdf = CAMReport(orientation='P', unit='mm', format='A4')
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_left_margin(25)
    pdf.set_right_margin(25)
    pdf.set_top_margin(20)
    
    # ── COVER PAGE ──
    pdf.add_page()
    usable_w = pdf.w - pdf.l_margin - pdf.r_margin
    
    pdf.ln(40)
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(11, 29, 81) # Navy #0B1D51
    pdf.multi_cell(usable_w, 12, "Credit Appraisal Memorandum", align="C")
    
    pdf.ln(10)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(usable_w, 10, _pdf_safe(company_name), align="C")
    
    pdf.ln(5)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(usable_w, 8, _pdf_safe(f"Application ID: {application_id}"), align="C", ln=1)
    
    pdf.ln(20)
    pdf.set_draw_color(11, 29, 81)
    pdf.set_line_width(0.5)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    
    pdf.ln(10)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(usable_w, 6, "Prepared by: IntelliCredit AI Engine", align="C", ln=1)
    pdf.cell(usable_w, 6, "For: Credit Committee Review", align="C", ln=1)
    pdf.ln(10)
    
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(180, 0, 0) # Muted red for notice
    pdf.multi_cell(usable_w, 5, "CONFIDENTIALITY NOTICE: This document contains proprietary credit analysis generated by the IntelliCredit AI Decision Engine. For internal use by Vivriti Capital only. Unauthorized distribution is strictly prohibited.", align="C")
    
    pdf.ln(10)
    pdf.set_draw_color(11, 29, 81)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    
    # ── CONTENT PAGES ──
    pdf.add_page()
    
    def render_markdown_table(pdf, table_lines, usable_w):
        if not table_lines: return
        rows = []
        for line in table_lines:
            if line.strip().startswith("|") and "---" not in line:
                cells = [c.strip() for c in line.strip("|").split("|")]
                rows.append(cells)
        if not rows: return
        
        col_count = max(len(r) for r in rows)
        col_w = usable_w / col_count
        
        for i, row in enumerate(rows):
            # Check for page break
            if pdf.get_y() > 260:
                pdf.add_page()
                
            if i == 0:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_fill_color(240, 240, 240)
                fill = True
            else:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_fill_color(255, 255, 255)
                fill = i % 2 == 0
            
            # Ensure row has enough cells
            row_cells = row + [""] * (col_count - len(row))
            
            for cell in row_cells:
                pdf.cell(col_w, 8, _pdf_safe(cell[:50]), border=1, fill=fill)
            pdf.ln()
        pdf.ln(5)

    lines = cam_markdown.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        
        # Table detection
        if line.strip().startswith("|"):
            table_lines = []
            while i < len(lines) and (lines[i].strip().startswith("|") or lines[i].strip() == ""):
                if lines[i].strip().startswith("|"):
                    table_lines.append(lines[i])
                i += 1
            render_markdown_table(pdf, table_lines, usable_w)
            continue

        clean = re.sub(r"\*\*(.*?)\*\*", r"\1", line)
        clean = re.sub(r"\*(.*?)\*", r"\1", clean)
        clean = _pdf_safe(clean)

        if line.startswith("# "):
            pdf.ln(5)
            pdf.set_font("Helvetica", "B", 16)
            pdf.set_text_color(11, 29, 81) # Navy #0B1D51
            pdf.multi_cell(usable_w, 8, clean[2:].strip())
            pdf.ln(2)
        elif line.startswith("## "):
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(11, 29, 81) # Navy #0B1D51
            pdf.multi_cell(usable_w, 7, clean[3:].strip())
            # FIX C: horizontal rule
            pdf.set_draw_color(200, 200, 200)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(3)
        elif line.startswith("### "):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(26, 26, 46) # Dark #1A1A2E
            pdf.multi_cell(usable_w, 6, clean[4:].strip())
            pdf.ln(1)
        elif line.startswith("- ") or line.startswith("* "):
            pdf.set_font("Helvetica", "", 10) # Body font 10pt
            pdf.set_text_color(0, 0, 0)
            # Bullet indent
            pdf.set_x(pdf.l_margin)
            pdf.cell(5, 6, _pdf_safe("•"))
            pdf.set_x(pdf.l_margin + 5)
            pdf.multi_cell(usable_w - 5, 6, clean[2:].strip())
        elif line.strip() and not line.startswith("---"):
            pdf.set_font("Helvetica", "", 10) # Body font 10pt
            pdf.set_text_color(0, 0, 0)
            # Body text wrapping
            pdf.multi_cell(usable_w, 6, clean)
        elif line.startswith("---"):
            pdf.ln(2)
            pdf.set_draw_color(230, 230, 230)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(4)
        
        i += 1

    if output_path is None:
        os.makedirs("./exports", exist_ok=True)
        output_path = f"./exports/CAM_{application_id}.pdf"

    pdf.output(output_path)
    return output_path
            
    if output_path is None:
        os.makedirs("./exports", exist_ok=True)
        output_path = f"./exports/CAM_{application_id}.pdf"

    pdf.output(output_path)
    return output_path
